### ISSUE TITLE
Keyboard Shortcut/Context Menu

### ISSUE THREAD

**Issue by gep13** [ziyasal/vscode-open-in-github#3]
Is it possible to have either a keyboard shortcut for this command, or an entry in the Context Menu when you right click on a file?

**Comment by ziyasal** [comment]
Hi @gep13  I'll examine how I put an entry to context menu. Sure, I'd like to bind a  Keyboard Short-cut for this (this is possible).

**Comment by gep13** [comment]
Perfect, thank you! :+1:

**Comment by ziyasal** [comment]
hi @gep13  I'll publish new version asap.

**Comment by ziyasal** [comment]
Hi @gep13, I've pushed new version.

**Comment by gep13** [comment]
@ziyasal can you confirm what version number this functionality will appear in?  I have 0.1.7 installed, and I still don't see those options.  Thanks!

**Comment by ziyasal** [comment]
Hi @gep13  This functionality has introduced in >=0.1.8
I think there is no option to upgrade extension, workaround for this you may delete it and reinstall new one (:

To navigate `extensions` folder,
 ```bash 
cd %USERPROFILE%\.vscode\extensions
```

Thanks.

**Comment by gep13** [comment]
@ziyasal no need to uninstall:

![image](https://cloud.githubusercontent.com/assets/1271146/11265799/3254dbc2-8e97-11e5-84eb-3cf486295602.png)

**Comment by gep13** [comment]
@ziyasal so this gives a keyboard shortcut, which is great:

![image](https://cloud.githubusercontent.com/assets/1271146/11265925/53f7ef66-8e98-11e5-9e1b-47aa6ee40a39.png)

Is it possible to also get a Context Menu when right clicking on a file?  Or is that functionality not exposed?

**Comment by ziyasal** [comment]
Hi @gep13, It should be `ext update` command, I think :) I couldn't  find reference docs about adding new entry to Context menu. Anyway,  I'll continue to examine.

**Comment by ziyasal** [comment]
@gep13 Ok I see, There is a little button to do that. Thanks.

**Comment by openingnow** [comment]
The keyboard shortcut deactivates `cmd+o`to open file/folders.
When I press `cmd+o`, vscode waits until second key is pressed - prevents pressing just `cmd+o`.
It happens same when I insert `{ "key": "cmd+o cmd+g", "command": ""}`at `keybinding.json`

As I don't want to change shortcut of opening files, I want to change shortcut of this extension.
Should I build the extension manually to change it?
